package com.example.kampa

import com.parse.ParseQuery

object Constantes {
    val ADMINISTRADOR = "administrador"
    val APROBADA = "aprobada"
    val CREATED_AT = "createdAt"
    val CURRENT_LOCATION = "currentLocation"
    val DESCRIPCION = "descripcion"
    val DIRECCION = "direccion"
    val ELIMINADA = "eliminada"
    val ESTADO = "estado"
    val FOTO = "foto"
    val FOTOS = "fotos"
    val FOTO_PERFIL = "fotoPerfil"
    val FOTO_WISHLIST = "fotoWishlist"
    val HISTORIA = "historia"
    val ID_PUBLICACION = "idPublicacion"
    val ID_ROL = "idRol"
    val ID_SITIO = "idSitio"
    val ID_TAG = "idTag"
    val ID_TIPO_SITIO = "idTipoSitio"
    val ID_USUARIO = "idUsuario"
    val ID_WISHLIST = "idWishlist"
    val IS_DELETED = "isDeleted"
    val IS_VISITADO = "isVisitado"
    val IS_WISHLIST = "isWishlist"
    val NOMBRE = "nombre"
    val NUM_DISLIKES = "numDislikes"
    val NUM_LIKES = "numLikes"
    val NUM_PUBLICACIONES = "numPublicaciones"
    val PAGINA_OFICIAL = "paginaOficial"
    val PERMISSION = "permission"
    val SITIO = "sitio"
    val UBICACION = "ubicacion"
    val WISHLIST = "wishlist"
    val OBJECT_ID = "objectId"
}
